### ISSUE TITLE
/master (GET)

### ISSUE THREAD

**Issue by rigobertopacheco26** [oscar-legorretam/aprecio#5]
Se debe proporcionar el valor de los catalogos siguientes:

"providerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "orderedUnitOfMeasureId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "fulfillmentUnitOfMeasureId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",

**Comment by oscar-legorretam** [comment]
ya existen endpoints para obtener todos los detalles necesarios, si hay algo que evite usarlos, por favor presenten el caso de uso para agregar un endpoint

**Comment by rigobertopacheco26** [comment]
Los datos de esta API se estarán mostrando en una tabla, el simple hecho de usar este metodo como comentas no es eficiente, favor de realizar tus adecuaciones para proporciona los nombre de cada uuid

**Comment by oscar-legorretam** [comment]
ya se retrabajo, puede haber bugs
